### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by tylernchls** [junior-devleague/spotify-playlist#1]
1. Fix bold markdown throughout the repo. Just need to add a space after the ####
2. **Before you begin section** - Specify that they either draw or whiteboard their idea that must be approved by the instructor.
3. Make a sanity check section before they even start typing any lines of code. Link html and css and show sanity check works to the instructor before moving forward.
4. Put the bonus in HTML section into **Stretch goals**
5. Should the shuffle button work???
6. Make the repo public

**Comment by zakattack9** [comment]
I added all your suggestions to the repo, however I don't think the shuffle button should work, mainly because it would require javascript to complete the task; nonetheless, thanks for the suggestions 👍
